/**
* SpeechToText
* This is an API for a Speech-to-Text component.
*
* The version of the OpenAPI document: 0.1.0
* Contact: norman.jansen@fkie.fraunhofer.de
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DefaultApi.h
 *
 * 
 */

#ifndef DefaultApi_H_
#define DefaultApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "Error.h"
#include "Provide_audio_request.h"
#include "_on_new_text_post_request.h"
#include <string>

namespace org::openapitools::speechtotext::server::api
{

class  DefaultApi : public ApiBase {
public:
    explicit DefaultApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~DefaultApi() override = default;
    void init() override;

    static const std::string base;

private:
    void setupRoutes();

    void initialize_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void on_new_text_post_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void provide_audio_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void default_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual void handleParsingException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual void handleOperationException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Initialize the SpeechToText component
    /// </summary>
    /// <remarks>
    /// Initialize the SpeechToText component
    /// </remarks>
    /// <param name="speechtotextVariant"></param>
    /// <param name="configProfile"></param>
    /// <param name="webhookUrl"></param>
    virtual void initialize(const std::optional<std::string> &speechtotextVariant, const std::optional<std::string> &configProfile, const std::optional<std::string> &webhookUrl, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="onNewTextPostRequest">Webhook for delivering new text from speech recognition to client (optional)</param>
    virtual void on_new_text_post(const org::openapitools::speechtotext::server::model::_on_new_text_post_request &onNewTextPostRequest, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Provide audio to the SpeechToText component
    /// </summary>
    /// <remarks>
    /// Provide audio to the SpeechToText component
    /// </remarks>
    /// <param name="provideAudioRequest">part of the audio (e.g. 20 ms) as byte array</param>
    virtual void provide_audio(const org::openapitools::speechtotext::server::model::Provide_audio_request &provideAudioRequest, Pistache::Http::ResponseWriter &response) = 0;

};

} // namespace org::openapitools::speechtotext::server::api

#endif /* DefaultApi_H_ */

