from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProvideTextRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timestamp_start=None, timestamp_end=None, message_id=None, text=None):  # noqa: E501
        """ProvideTextRequest - a model defined in OpenAPI

        :param timestamp_start: The timestamp_start of this ProvideTextRequest.  # noqa: E501
        :type timestamp_start: int
        :param timestamp_end: The timestamp_end of this ProvideTextRequest.  # noqa: E501
        :type timestamp_end: int
        :param message_id: The message_id of this ProvideTextRequest.  # noqa: E501
        :type message_id: str
        :param text: The text of this ProvideTextRequest.  # noqa: E501
        :type text: str
        """
        self.openapi_types = {
            'timestamp_start': int,
            'timestamp_end': int,
            'message_id': str,
            'text': str
        }

        self.attribute_map = {
            'timestamp_start': 'timestamp_start',
            'timestamp_end': 'timestamp_end',
            'message_id': 'message_id',
            'text': 'text'
        }

        self._timestamp_start = timestamp_start
        self._timestamp_end = timestamp_end
        self._message_id = message_id
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'ProvideTextRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The provide_text_request of this ProvideTextRequest.  # noqa: E501
        :rtype: ProvideTextRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp_start(self) -> int:
        """Gets the timestamp_start of this ProvideTextRequest.

        timestamp (start) of the text corresponding to the audio samples in ms  # noqa: E501

        :return: The timestamp_start of this ProvideTextRequest.
        :rtype: int
        """
        return self._timestamp_start

    @timestamp_start.setter
    def timestamp_start(self, timestamp_start: int):
        """Sets the timestamp_start of this ProvideTextRequest.

        timestamp (start) of the text corresponding to the audio samples in ms  # noqa: E501

        :param timestamp_start: The timestamp_start of this ProvideTextRequest.
        :type timestamp_start: int
        """

        self._timestamp_start = timestamp_start

    @property
    def timestamp_end(self) -> int:
        """Gets the timestamp_end of this ProvideTextRequest.

        timestamp (end) of the text corresponding to the audio samples in ms  # noqa: E501

        :return: The timestamp_end of this ProvideTextRequest.
        :rtype: int
        """
        return self._timestamp_end

    @timestamp_end.setter
    def timestamp_end(self, timestamp_end: int):
        """Sets the timestamp_end of this ProvideTextRequest.

        timestamp (end) of the text corresponding to the audio samples in ms  # noqa: E501

        :param timestamp_end: The timestamp_end of this ProvideTextRequest.
        :type timestamp_end: int
        """

        self._timestamp_end = timestamp_end

    @property
    def message_id(self) -> str:
        """Gets the message_id of this ProvideTextRequest.


        :return: The message_id of this ProvideTextRequest.
        :rtype: str
        """
        return self._message_id

    @message_id.setter
    def message_id(self, message_id: str):
        """Sets the message_id of this ProvideTextRequest.


        :param message_id: The message_id of this ProvideTextRequest.
        :type message_id: str
        """

        self._message_id = message_id

    @property
    def text(self) -> str:
        """Gets the text of this ProvideTextRequest.


        :return: The text of this ProvideTextRequest.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this ProvideTextRequest.


        :param text: The text of this ProvideTextRequest.
        :type text: str
        """

        self._text = text
