from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Error(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error_message=None, detail=None):  # noqa: E501
        """Error - a model defined in OpenAPI

        :param error_message: The error_message of this Error.  # noqa: E501
        :type error_message: str
        :param detail: The detail of this Error.  # noqa: E501
        :type detail: object
        """
        self.openapi_types = {
            'error_message': str,
            'detail': object
        }

        self.attribute_map = {
            'error_message': 'error_message',
            'detail': 'detail'
        }

        self._error_message = error_message
        self._detail = detail

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_message(self) -> str:
        """Gets the error_message of this Error.


        :return: The error_message of this Error.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this Error.


        :param error_message: The error_message of this Error.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def detail(self) -> object:
        """Gets the detail of this Error.


        :return: The detail of this Error.
        :rtype: object
        """
        return self._detail

    @detail.setter
    def detail(self, detail: object):
        """Sets the detail of this Error.


        :param detail: The detail of this Error.
        :type detail: object
        """

        self._detail = detail
