from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class OnNewTextPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timestamp_start=None, timestamp_end=None, text=None):  # noqa: E501
        """OnNewTextPostRequest - a model defined in OpenAPI

        :param timestamp_start: The timestamp_start of this OnNewTextPostRequest.  # noqa: E501
        :type timestamp_start: int
        :param timestamp_end: The timestamp_end of this OnNewTextPostRequest.  # noqa: E501
        :type timestamp_end: int
        :param text: The text of this OnNewTextPostRequest.  # noqa: E501
        :type text: str
        """
        self.openapi_types = {
            'timestamp_start': int,
            'timestamp_end': int,
            'text': str
        }

        self.attribute_map = {
            'timestamp_start': 'timestamp_start',
            'timestamp_end': 'timestamp_end',
            'text': 'text'
        }

        self._timestamp_start = timestamp_start
        self._timestamp_end = timestamp_end
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'OnNewTextPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _on_new_text_post_request of this OnNewTextPostRequest.  # noqa: E501
        :rtype: OnNewTextPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp_start(self) -> int:
        """Gets the timestamp_start of this OnNewTextPostRequest.

        timestamp (start) of the text corresponding to the audio samples  # noqa: E501

        :return: The timestamp_start of this OnNewTextPostRequest.
        :rtype: int
        """
        return self._timestamp_start

    @timestamp_start.setter
    def timestamp_start(self, timestamp_start: int):
        """Sets the timestamp_start of this OnNewTextPostRequest.

        timestamp (start) of the text corresponding to the audio samples  # noqa: E501

        :param timestamp_start: The timestamp_start of this OnNewTextPostRequest.
        :type timestamp_start: int
        """

        self._timestamp_start = timestamp_start

    @property
    def timestamp_end(self) -> int:
        """Gets the timestamp_end of this OnNewTextPostRequest.

        timestamp (end) of the text corresponding to the audio samples  # noqa: E501

        :return: The timestamp_end of this OnNewTextPostRequest.
        :rtype: int
        """
        return self._timestamp_end

    @timestamp_end.setter
    def timestamp_end(self, timestamp_end: int):
        """Sets the timestamp_end of this OnNewTextPostRequest.

        timestamp (end) of the text corresponding to the audio samples  # noqa: E501

        :param timestamp_end: The timestamp_end of this OnNewTextPostRequest.
        :type timestamp_end: int
        """

        self._timestamp_end = timestamp_end

    @property
    def text(self) -> str:
        """Gets the text of this OnNewTextPostRequest.


        :return: The text of this OnNewTextPostRequest.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this OnNewTextPostRequest.


        :param text: The text of this OnNewTextPostRequest.
        :type text: str
        """

        self._text = text
