---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(levelname)-8s:%(name)-25s: %(message)s"
        datefmt: "%d/%m/%Y %H:%M:%S"
    color:
        format: "%(asctime)s %(levelname)-8s:%(name)-25s: %(message)s"
        (): __main__.ColoredFormatter
        use_color: true

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: color
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: logs/audio_experiments.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info_audio_experiments.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors_audio_experiments.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler, debug_file_handler]
