/**
* SpeechToText
* This is an API for a Speech-to-Text component.
*
* The version of the OpenAPI document: 0.1.0
* Contact: norman.jansen@fkie.fraunhofer.de
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Provide_audio_request.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::speechtotext::server::model
{

Provide_audio_request::Provide_audio_request()
{
    m_Length = 0;
    m_LengthIsSet = false;
    m_Sample_rate_hz = 0;
    m_Sample_rate_hzIsSet = false;
    m_Timestamp = 0;
    m_TimestampIsSet = false;
    m_Byte_arrayIsSet = false;
    
}

void Provide_audio_request::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::speechtotext::server::helpers::ValidationException(msg.str());
    }
}

bool Provide_audio_request::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Provide_audio_request::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Provide_audio_request" : pathPrefix;

                    
    return success;
}

bool Provide_audio_request::operator==(const Provide_audio_request& rhs) const
{
    return
    
    
    
    ((!lengthIsSet() && !rhs.lengthIsSet()) || (lengthIsSet() && rhs.lengthIsSet() && getLength() == rhs.getLength())) &&
    
    
    ((!sampleRateHzIsSet() && !rhs.sampleRateHzIsSet()) || (sampleRateHzIsSet() && rhs.sampleRateHzIsSet() && getSampleRateHz() == rhs.getSampleRateHz())) &&
    
    
    ((!timestampIsSet() && !rhs.timestampIsSet()) || (timestampIsSet() && rhs.timestampIsSet() && getTimestamp() == rhs.getTimestamp())) &&
    
    
    ((!byteArrayIsSet() && !rhs.byteArrayIsSet()) || (byteArrayIsSet() && rhs.byteArrayIsSet() && getByteArray() == rhs.getByteArray()))
    
    ;
}

bool Provide_audio_request::operator!=(const Provide_audio_request& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Provide_audio_request& o)
{
    j = nlohmann::json::object();
    if(o.lengthIsSet())
        j["length"] = o.m_Length;
    if(o.sampleRateHzIsSet())
        j["sample_rate_hz"] = o.m_Sample_rate_hz;
    if(o.timestampIsSet())
        j["timestamp"] = o.m_Timestamp;
    if(o.byteArrayIsSet())
        j["byte_array"] = o.m_Byte_array;
    
}

void from_json(const nlohmann::json& j, Provide_audio_request& o)
{
    if(j.find("length") != j.end())
    {
        j.at("length").get_to(o.m_Length);
        o.m_LengthIsSet = true;
    } 
    if(j.find("sample_rate_hz") != j.end())
    {
        j.at("sample_rate_hz").get_to(o.m_Sample_rate_hz);
        o.m_Sample_rate_hzIsSet = true;
    } 
    if(j.find("timestamp") != j.end())
    {
        j.at("timestamp").get_to(o.m_Timestamp);
        o.m_TimestampIsSet = true;
    } 
    if(j.find("byte_array") != j.end())
    {
        j.at("byte_array").get_to(o.m_Byte_array);
        o.m_Byte_arrayIsSet = true;
    } 
    
}

int32_t Provide_audio_request::getLength() const
{
    return m_Length;
}
void Provide_audio_request::setLength(int32_t const value)
{
    m_Length = value;
    m_LengthIsSet = true;
}
bool Provide_audio_request::lengthIsSet() const
{
    return m_LengthIsSet;
}
void Provide_audio_request::unsetLength()
{
    m_LengthIsSet = false;
}
int32_t Provide_audio_request::getSampleRateHz() const
{
    return m_Sample_rate_hz;
}
void Provide_audio_request::setSampleRateHz(int32_t const value)
{
    m_Sample_rate_hz = value;
    m_Sample_rate_hzIsSet = true;
}
bool Provide_audio_request::sampleRateHzIsSet() const
{
    return m_Sample_rate_hzIsSet;
}
void Provide_audio_request::unsetSample_rate_hz()
{
    m_Sample_rate_hzIsSet = false;
}
int64_t Provide_audio_request::getTimestamp() const
{
    return m_Timestamp;
}
void Provide_audio_request::setTimestamp(int32_t const value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}
bool Provide_audio_request::timestampIsSet() const
{
    return m_TimestampIsSet;
}
void Provide_audio_request::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
std::string Provide_audio_request::getByteArray() const
{
    return m_Byte_array;
}
void Provide_audio_request::setByteArray(std::string const& value)
{
    m_Byte_array = value;
    m_Byte_arrayIsSet = true;
}
bool Provide_audio_request::byteArrayIsSet() const
{
    return m_Byte_arrayIsSet;
}
void Provide_audio_request::unsetByte_array()
{
    m_Byte_arrayIsSet = false;
}


} // namespace org::openapitools::speechtotext::server::model

