/**
* MqttTransport
* This is an API for a MQTT-Transport component.
*
* The version of the OpenAPI document: 0.1.0
* Contact: norman.jansen@fkie.fraunhofer.de
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DefaultApi.h
 *
 * 
 */

#ifndef DefaultApi_H_
#define DefaultApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "Error.h"
#include "Message.h"
#include <string>

namespace org::openapitools::mqtttransport::server::api
{

class  DefaultApi : public ApiBase {
public:
    explicit DefaultApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~DefaultApi() override = default;
    void init() override;

    static const std::string base;

private:
    void setupRoutes();

    void initialize_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void on_new_message_post_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void send_message_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void default_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual void handleParsingException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual void handleOperationException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Initialize the MQTT-Transport component
    /// </summary>
    /// <remarks>
    /// Initialize the MQTT-Transport component
    /// </remarks>
    /// <param name="mqttVariant"></param>
    /// <param name="configProfile"></param>
    /// <param name="baseTopic"></param>
    /// <param name="nodeId"></param>
    /// <param name="webhookUrl"></param>
    /// <param name="mqttServerIp"> (optional, default to &quot;&quot;)</param>
    /// <param name="mqttServerPort"> (optional, default to 0)</param>
    virtual void initialize(const std::optional<std::string> &mqttVariant, const std::optional<std::string> &configProfile, const std::optional<std::string> &baseTopic, const std::optional<std::string> &nodeId, const std::optional<std::string> &webhookUrl, const std::optional<std::string> &mqttServerIp, const std::optional<int32_t> &mqttServerPort, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="message">Webhook for receiving message from MQTT Transport component</param>
    virtual void on_new_message_post(const org::openapitools::mqtttransport::server::model::Message &message, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Send message via MQTT Transport component
    /// </summary>
    /// <remarks>
    /// Send message via MQTT Transport component
    /// </remarks>
    /// <param name="source">IP address of the source.</param>
    /// <param name="destination">IP address of the destination (optional, broadcast if not specified). (optional, default to &quot;&quot;)</param>
    /// <param name="message">the message (optional)</param>
    virtual void send_message(const std::optional<std::string> &source, const std::optional<std::string> &destination, const org::openapitools::mqtttransport::server::model::Message &message, Pistache::Http::ResponseWriter &response) = 0;

};

} // namespace org::openapitools::mqtttransport::server::api

#endif /* DefaultApi_H_ */

