openapi: 3.0.0
info:
  contact:
    email: norman.jansen@fkie.fraunhofer.de
  description: This is an API for a Text-to-Speech component.
  title: TextToSpeech
  version: 0.1.0
servers:
- url: http://localhost:8082/texttospeech
paths:
  /initialize:
    put:
      description: Initialize the TextToSpeech component
      operationId: initialize
      parameters:
      - explode: true
        in: query
        name: texttospeech_variant
        required: true
        schema:
          enum:
            - standard
            - coqui_yourtts
            - coqui_xtts
          type: string
        style: form
      - explode: true
        in: query
        name: config_profile
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: webhook_url
        required: true
        schema:
          title: text
          type: string
        style: form
      responses:
        "200":
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
      summary: Initialize the TextToSpeech component
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /on_new_audio:
    post:
      operationId: on_new_audio_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_on_new_audio_post_request'
        description: Webhook for geting part of the audio as byte array corresponding
          to the text provided
        required: true
      responses:
        "200":
          description: Webhook acknowledged
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /provide_text:
    post:
      description: Provide text to the TextToSpeech component
      operationId: provide_text
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/provide_text_request'
        description: text for the TextToSpeech component
        required: true
      responses:
        "200":
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
      summary: Provide text to the TextToSpeech component
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Error:
      example:
        error_message: error_message
        detail: "{}"
      properties:
        error_message:
          title: error_message
          type: string
        detail:
          title: detail
          type: object
      title: Error
    provide_text_request:
      properties:
        timestamp_start:
          description: timestamp (start) of the text corresponding to the audio samples
            in ms
          format: int64
          title: timestamp_start
          type: integer
        timestamp_end:
          description: timestamp (end) of the text corresponding to the audio samples
            in ms
          format: int64
          title: timestamp_end
          type: integer
        message_id:
          title: message_id
          type: string
        text:
          title: text
          type: string
      title: provide_text_request
    _on_new_audio_post_request:
      properties:
        length:
          description: length of the audio in bytes.
          example: "640   # 16 kHz * 20 ms * 16 Bit"
          title: length
          type: integer
        sample_rate_hz:
          description: sample rate in hz.
          example: "16000"
          title: sample_rate_hz
          type: integer
        timestamp:
          description: timestamp of the start of the audio samples in ms
          format: int64
          title: timestamp
          type: integer
        message_id:
          title: message_id
          type: string
        byte_array:
          description: base64 encoded binary content.
          format: byte
          title: byte_array
          type: string
      title: _on_new_audio_post_request
