/**
* TextToSpeech
* This is an API for a Text-to-Speech component.
*
* The version of the OpenAPI document: 0.1.0
* Contact: norman.jansen@fkie.fraunhofer.de
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* DefaultApiImpl.h
*
* 
*/

#ifndef DEFAULT_TEXTTOSPEECH_API_IMPL_H_
#define DEFAULT_TEXTTOSPEECH_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include "../api/DefaultApi.h"


#include "../model/Error.h"
#include "../model/Provide_text_request.h"
#include "../model/_on_new_audio_post_request.h"
#include <string>

namespace org::openapitools::texttospeech::server::api
{

using namespace org::openapitools::texttospeech::server::model;

class  DefaultApiImpl : public org::openapitools::texttospeech::server::api::DefaultApi {
public:
    explicit DefaultApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~DefaultApiImpl() override = default;

    void initialize(const std::optional<std::string> &texttospeechVariant, const std::optional<std::string> &configProfile, const std::optional<std::string> &webhookUrl, Pistache::Http::ResponseWriter &response);
    void on_new_audio_post(const _on_new_audio_post_request &onNewAudioPostRequest, Pistache::Http::ResponseWriter &response);
    void provide_text(const Provide_text_request &provideTextRequest, Pistache::Http::ResponseWriter &response);

};

} // namespace org::openapitools::texttospeech::server::api



#endif
