/**
* TextToSpeech
* This is an API for a Text-to-Speech component.
*
* The version of the OpenAPI document: 0.1.0
* Contact: norman.jansen@fkie.fraunhofer.de
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DefaultApi.h
 *
 * 
 */

#ifndef DefaultApi_H_
#define DefaultApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "Error.h"
#include "Provide_text_request.h"
#include "_on_new_audio_post_request.h"
#include <string>

namespace org::openapitools::texttospeech::server::api
{

class  DefaultApi : public ApiBase {
public:
    explicit DefaultApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~DefaultApi() override = default;
    void init() override;

    static const std::string base;

private:
    void setupRoutes();

    void initialize_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void on_new_audio_post_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void provide_text_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void default_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual void handleParsingException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual void handleOperationException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Initialize the TextToSpeech component
    /// </summary>
    /// <remarks>
    /// Initialize the TextToSpeech component
    /// </remarks>
    /// <param name="texttospeechVariant"></param>
    /// <param name="configProfile"></param>
    /// <param name="webhookUrl"></param>
    virtual void initialize(const std::optional<std::string> &texttospeechVariant, const std::optional<std::string> &configProfile, const std::optional<std::string> &webhookUrl, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="onNewAudioPostRequest">Webhook for geting part of the audio as byte array corresponding to the text provided</param>
    virtual void on_new_audio_post(const org::openapitools::texttospeech::server::model::_on_new_audio_post_request &onNewAudioPostRequest, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Provide text to the TextToSpeech component
    /// </summary>
    /// <remarks>
    /// Provide text to the TextToSpeech component
    /// </remarks>
    /// <param name="provideTextRequest">text for the TextToSpeech component</param>
    virtual void provide_text(const org::openapitools::texttospeech::server::model::Provide_text_request &provideTextRequest, Pistache::Http::ResponseWriter &response) = 0;

};

} // namespace org::openapitools::texttospeech::server::api

#endif /* DefaultApi_H_ */

