/**
* SpeechToText
* This is an API for a Speech-to-Text component.
*
* The version of the OpenAPI document: 0.1.0
* Contact: norman.jansen@fkie.fraunhofer.de
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Error.h
 *
 * 
 */

#ifndef Error_H_
#define Error_H_


#include <nlohmann/json.hpp>
#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::speechtotext::server::model
{

/// <summary>
/// 
/// </summary>
class  Error
{
public:
    Error();
    virtual ~Error() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Error& rhs) const;
    bool operator!=(const Error& rhs) const;

    /////////////////////////////////////////////
    /// Error members

    /// <summary>
    /// 
    /// </summary>
    std::string getErrorMessage() const;
    void setErrorMessage(std::string const& value);
    bool errorMessageIsSet() const;
    void unsetError_message();
    /// <summary>
    /// 
    /// </summary>
    nlohmann::json getDetail() const;
    void setDetail(nlohmann::json const& value);
    bool detailIsSet() const;
    void unsetDetail();

    friend  void to_json(nlohmann::json& j, const Error& o);
    friend  void from_json(const nlohmann::json& j, Error& o);
protected:
    std::string m_Error_message;
    bool m_Error_messageIsSet;
    nlohmann::json m_Detail;
    bool m_DetailIsSet;
    
};

} // namespace org::openapitools::speechtotext::server::model

#endif /* Error_H_ */
