/**
* TextToSpeech
* This is an API for a Text-to-Speech component.
*
* The version of the OpenAPI document: 0.1.0
* Contact: norman.jansen@fkie.fraunhofer.de
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Provide_text_request.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::texttospeech::server::model
{

Provide_text_request::Provide_text_request()
{
    m_Timestamp_start = 0L;
    m_Timestamp_startIsSet = false;
    m_Timestamp_end = 0L;
    m_Timestamp_endIsSet = false;
    m_Message_id = "";
    m_Message_idIsSet = false;
    m_Text = "";
    m_TextIsSet = false;
    
}

void Provide_text_request::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::texttospeech::server::helpers::ValidationException(msg.str());
    }
}

bool Provide_text_request::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Provide_text_request::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Provide_text_request" : pathPrefix;

                    
    return success;
}

bool Provide_text_request::operator==(const Provide_text_request& rhs) const
{
    return
    
    
    
    ((!timestampStartIsSet() && !rhs.timestampStartIsSet()) || (timestampStartIsSet() && rhs.timestampStartIsSet() && getTimestampStart() == rhs.getTimestampStart())) &&
    
    
    ((!timestampEndIsSet() && !rhs.timestampEndIsSet()) || (timestampEndIsSet() && rhs.timestampEndIsSet() && getTimestampEnd() == rhs.getTimestampEnd())) &&
    
    
    ((!messageIdIsSet() && !rhs.messageIdIsSet()) || (messageIdIsSet() && rhs.messageIdIsSet() && getMessageId() == rhs.getMessageId())) &&
    
    
    ((!textIsSet() && !rhs.textIsSet()) || (textIsSet() && rhs.textIsSet() && getText() == rhs.getText()))
    
    ;
}

bool Provide_text_request::operator!=(const Provide_text_request& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Provide_text_request& o)
{
    j = nlohmann::json::object();
    if(o.timestampStartIsSet())
        j["timestamp_start"] = o.m_Timestamp_start;
    if(o.timestampEndIsSet())
        j["timestamp_end"] = o.m_Timestamp_end;
    if(o.messageIdIsSet())
        j["message_id"] = o.m_Message_id;
    if(o.textIsSet())
        j["text"] = o.m_Text;
    
}

void from_json(const nlohmann::json& j, Provide_text_request& o)
{
    if(j.find("timestamp_start") != j.end())
    {
        j.at("timestamp_start").get_to(o.m_Timestamp_start);
        o.m_Timestamp_startIsSet = true;
    } 
    if(j.find("timestamp_end") != j.end())
    {
        j.at("timestamp_end").get_to(o.m_Timestamp_end);
        o.m_Timestamp_endIsSet = true;
    } 
    if(j.find("message_id") != j.end())
    {
        j.at("message_id").get_to(o.m_Message_id);
        o.m_Message_idIsSet = true;
    } 
    if(j.find("text") != j.end())
    {
        j.at("text").get_to(o.m_Text);
        o.m_TextIsSet = true;
    } 
    
}

int64_t Provide_text_request::getTimestampStart() const
{
    return m_Timestamp_start;
}
void Provide_text_request::setTimestampStart(int64_t const value)
{
    m_Timestamp_start = value;
    m_Timestamp_startIsSet = true;
}
bool Provide_text_request::timestampStartIsSet() const
{
    return m_Timestamp_startIsSet;
}
void Provide_text_request::unsetTimestamp_start()
{
    m_Timestamp_startIsSet = false;
}
int64_t Provide_text_request::getTimestampEnd() const
{
    return m_Timestamp_end;
}
void Provide_text_request::setTimestampEnd(int64_t const value)
{
    m_Timestamp_end = value;
    m_Timestamp_endIsSet = true;
}
bool Provide_text_request::timestampEndIsSet() const
{
    return m_Timestamp_endIsSet;
}
void Provide_text_request::unsetTimestamp_end()
{
    m_Timestamp_endIsSet = false;
}
std::string Provide_text_request::getMessageId() const
{
    return m_Message_id;
}
void Provide_text_request::setMessageId(std::string const& value)
{
    m_Message_id = value;
    m_Message_idIsSet = true;
}
bool Provide_text_request::messageIdIsSet() const
{
    return m_Message_idIsSet;
}
void Provide_text_request::unsetMessage_id()
{
    m_Message_idIsSet = false;
}
std::string Provide_text_request::getText() const
{
    return m_Text;
}
void Provide_text_request::setText(std::string const& value)
{
    m_Text = value;
    m_TextIsSet = true;
}
bool Provide_text_request::textIsSet() const
{
    return m_TextIsSet;
}
void Provide_text_request::unsetText()
{
    m_TextIsSet = false;
}


} // namespace org::openapitools::texttospeech::server::model

